train:
  TRAIN_DIR: ARVCTRUSS/train/ply_xyzlabelnormal_ground_filtered_RANSAC_1metro
  VALID_DIR: ARVCTRUSS/valid/ply_xyzlabelnormal
  # IF USE_VALID_DATA set to False TRAIN_DATA will be split using TRAIN_SPLIT
  USE_VALID_DATA: False
  TRAIN_SPLIT: 0.8
  OUTPUT_DIR: model_save
  FEATURES: [0,1,2,4,5,6]
  LABELS: 3
  NORMALIZE: True
  BINARY: True
  DEVICE: cpu # cuda:X, cpu
  BATCH_SIZE: 2
  EPOCHS: 50
  LR: 0.001
  OUTPUT_CLASSES: 1
  THRESHOLD_METHOD: pr # roc, pr, tuning
  TERMINATION_CRITERIA: loss # loss, precision, f1_score
  EPOCH_TIMEOUT: 5

test:
  TEST_DIR: ARVCTRUSS/test/ply_xyzlabelnormal
  DEVICE: cuda:0
  BATCH_SIZE: 1
  SAVE_PRED_CLOUDS: False
