# DATASET
DATASET_DIR: ARVCTRUSS/code_test/ply_xyzlabelnormal
OUTPUT_DIR: model_save
TRAIN_SPLIT: 0.8
FEATURES: [0,1,2]
LABELS: 3
NORMALIZE: True
BINARY: True
# THRESHOLD_METHOS POSIBILITIES = cuda:X, cpu
DEVICE: cpu
BATCH_SIZE: 16
EPOCHS: 50
LR: 0.001
# MODEL
OUTPUT_CLASSES: 1
# THRESHOLD_METHOS POSIBILITIES = roc, pr, tuning
THRESHOLD_METHOD: pr
# TERMINATION_CRITERIA POSIBILITIES = loss, precision, f1_score
TERMINATION_CRITERIA: precision
EPOCH_TIMEOUT: 5